### ISSUE TITLE
Integrate into Django project?

### ISSUE THREAD

**Issue by soyapark** [moggers87/salmon#120]
I try to use salmon in my django project (1.7>=), and when I try to access django ORM in salmon router code, it raises `AppRegistryNotReady: Models aren't loaded yet.`. Any suggestion how to use django & salmon? Popular answers from google is `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "http_handler.settings")` and django.setup() but it does not work for salmon projects.

**Comment by moggers87** [comment]
Where are you putting this code? It should be in your Salmon settings module (default is `confg.settings`)

**Comment by soyapark** [comment]
Thanks for the quick response! 

I tried config.settings, config.boot and in router function! None of them worked for me. This is my settings.py atm. And it throws AppregistryNotReady exception at `django.setup()`

```
import sys
import logging


# You may add additional parameters such as `username' and `password' if your
# relay server requires authentication, `starttls' (boolean) or `ssl' (boolean)
# for secure connections.
relay_config = {'host': 'localhost', 'port': 8825 }


receiver_config = {'host': 'localhost', 'port': 8823}

handlers = ['zzz.test']

# hook django
import os
import django 
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "http_handler.settings")

django.setup()
# the config/boot.py will turn these values into variables set in settings
```

**Comment by moggers87** [comment]
Hmm, that's strange. I use the same code in my own Salmon+Django projects and they work fine.

What happens if you run this in the same environment?:

```python -c 'import os, django; os.environ.setdefault("DJANGO_SETTINGS_MODULE", "http_handler.settings"); django.setup()'```

**Comment by soyapark** [comment]
Nothing happened! Presumably that means no error? 

When I try to make a singleton python script then `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "http_handler.settings"); django.setup()` in there, it perfectly works! It only raises exception when I try to access django orm in salmon router functions. 

Just to double check, at your project, the way you turn on the project is `python manage.py runserver` and `salmon start` right? My django is under wsgi so I reboot my webserver and salmon separately when I update my codebase.

**Comment by moggers87** [comment]
Nothing happening means no error, which is a bit annoying as I was hoping that would reveal what the issue was.

Are you able to post the full stacktrace?

**Comment by moggers87** [comment]
And to answer your other question: yes, the WSGI app and Salmon app separately

**Comment by soyapark** [comment]
Should salmon app be included in a list of INSTALLED_APPS? (No matter adding the app or not, it does not work tho with the current setting :p )


> Nothing happening means no error, which is a bit annoying as I was hoping that would reveal what the issue was.
> 
> Are you able to post the full stacktrace that you're getting from Salmon?

Sure! Thank you so much for the help!


```
Traceback (most recent call last):
  File "/usr/local/bin/salmon", line 11, in <module>
    load_entry_point('salmon-mail==3.1.1', 'console_scripts', 'salmon')()
  File "/usr/local/lib/python2.7/site-packages/salmon/commands.py", line 65, in main
    cmd(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/salmon/commands.py", line 161, in command
    lambda: utils.import_settings(True, boot_module=boot), debug, daemon)
  File "/usr/local/lib/python2.7/site-packages/salmon/utils.py", line 119, in start_server
    settings = settings_loader()
  File "/usr/local/lib/python2.7/site-packages/salmon/commands.py", line 161, in <lambda>
    lambda: utils.import_settings(True, boot_module=boot), debug, daemon)
  File "/usr/local/lib/python2.7/site-packages/salmon/utils.py", line 33, in import_settings
    settings = importlib.import_module(settings_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/production/mailx/config/settings.py", line 26, in <module>
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 197, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/registration/models.py", line 15, in <module>
    User = get_user_model()
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 136, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by soyapark** [comment]
Hi! I just realize one of apps I have was using an outdated `django-registration`! As I updated its version, everything starts working! Whoa I still don't know why the exception only occurs during Salmon route tho!

Thanks for confirming the settings. It was greatly helpful! Please keep up great work! We love Salmon!
