### ISSUE TITLE
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

### ISSUE THREAD

**Issue by moggers87** [moggers87/salmon#166]
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pyproject_api/_backend.py", line 90, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyproject_api/_backend.py", line 32, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moggers/workspace/salmon/.tox/.pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
    self.run_setup()
  File "/home/moggers/workspace/salmon/.tox/.pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/moggers/workspace/salmon/.tox/.pkg/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 29, in <module>
  File "/home/moggers/workspace/salmon/versioneer.py", line 1476, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/home/moggers/workspace/salmon/versioneer.py", line 1408, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moggers/workspace/salmon/versioneer.py", line 338, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

**Comment by moggers87** [comment]
This happens in :fish: and in latest from PyPI

**Comment by moggers87** [comment]
Fixed by efd10274dc632c37bc8d1f0899755f0c92e03881
